### ISSUE TITLE
final result table uploaded

### ISSUE THREAD

**Issue by royxue** [royxue/MobileAnalysis#1]
@julian-ramos 
Hi, Julian
I just uploaded the final result table

**Comment by julian-ramos** [comment]
Cool, I will check tomorrow and then we can talk about next steps.

Thanks,

**Comment by julian-ramos** [comment]
Hi Roy,

This week got a little crazy due to several issues so I don't think I will
be able to look at the results this week. I will however have this ready
first thing for next week.

In the mean time lets plan to have a small talk over skype or gtalk about
the next steps.

My available times are anything from 8am to 12pm except MWF 12:30 to 1:30.
When would you like to talk?

Best regards,

On Tue, Nov 11, 2014 at 12:44 PM, Julian R. ing.julianr@gmail.com wrote:

> Cool, I will check tomorrow and then we can talk about next steps.
> 
> Thanks,
> On Nov 11, 2014 9:31 AM, "Roy Xue" notifications@github.com wrote:
> 
> > @julian-ramos https://github.com/julian-ramos
> > Hi, Julian
> > I just uploaded the final result table
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/RoyXue/MobileAnalysis/issues/1.

## 

Julian.

**Comment by royxue** [comment]
Hi, Julian

My Skype is xljroy, if you cannot find me, use xljroy@gmail.com, this is also my gtalk account.

I guess most time  is ok for me, I will keep my Skype online, if you are free to talk, just send a message to me, I will reply asap:)

Another thing, aha, I got my TOEFL score yesterday, it’s a good result, and thanks for your advices :)

Best Regards
— 
Xue Lijun Roy
http://www.royxue.me/

On November 13, 2014 at 2:38:39 AM, Julian Ramos (notifications@github.com) wrote:

Hi Roy,

This week got a little crazy due to several issues so I don't think I will
be able to look at the results this week. I will however have this ready
first thing for next week.

In the mean time lets plan to have a small talk over skype or gtalk about
the next steps.

My available times are anything from 8am to 12pm except MWF 12:30 to 1:30.
When would you like to talk?

Best regards,

On Tue, Nov 11, 2014 at 12:44 PM, Julian R. ing.julianr@gmail.com wrote:

> Cool, I will check tomorrow and then we can talk about next steps.
> 
> Thanks,
> On Nov 11, 2014 9:31 AM, "Roy Xue" notifications@github.com wrote:
> 
> > @julian-ramos https://github.com/julian-ramos
> > Hi, Julian
> > I just uploaded the final result table
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/RoyXue/MobileAnalysis/issues/1.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
Hi, when shall we meet this week>?

**Comment by julian-ramos** [comment]
Hi Roy,

I haven't gone trough the results yet. Though I finally managed to actually
get the data itself into a database. I still need to check on a couple of
things but let's say for now we could talk tomorrow at this time?

On Mon, Nov 17, 2014 at 8:20 PM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> Hi, when shall we meet this week>?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoyXue/MobileAnalysis/issues/1#issuecomment-63407470.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
Ok, see you tomorrow :)

**Comment by julian-ramos** [comment]
Ok so tomorrow at 8:30pm my time

On Mon, Nov 17, 2014 at 8:24 PM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> Ok, see you tomorrow :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoyXue/MobileAnalysis/issues/1#issuecomment-63407793.

## 

Julian.
