### ISSUE TITLE
Categories merging review

### ISSUE THREAD

**Issue by julian-ramos** [royxue/MobileAnalysis#3]
Lifestyle shouldn't be with health or medical. 

Health and medical definitely together just call it health(things you have to do to make your life better)
LIfestyle category should contain Sports (things you do everyday to make your life better)
Libraries and demo is a separate category should not be merged with any other category 
Finance category is fine meaning: finance together with shopping and business (selling buying stuff)
Entertainment category should contain: Music and audio, Photography, Media and Video, news and magazines and comics (self explanatory)
Personalization together with tools, live wallpaper, widgets, (personalization of your device)
Travel together with transportation (travel in general)
The games category  is just all of the games together.
Communication alone
Education alone
Books and reference alone
Social alone
Weather alone
Unknown also alone

I think this way we have covered all of the categories. Sorry for all of the back and forth, this is the final categorization. You should get 15 categories in total, let me know if we left any category outside.

**Comment by julian-ramos** [comment]
Once you update your code to reflect this merging you can run again the clustering algorithm. There is something strange going on with the standard deviation it is always zero and that is very unlikely so check if the clustering algorithm needs some random seed that you have to change every time. Also since the silhouette is not the most reliable score can you also compute the gap statistic here a link https://stat.ethz.ch/R-manual/R-devel/library/cluster/html/clusGap.html from it also compute average and standard deviation.

**Comment by julian-ramos** [comment]
Last during the merging of the categories do it for the normalized values, I think you are already doing that way meaning for example:
Category A=[0.2 0.3 0.5]
Category B=[0.3 0.4 0.3]
merged = [0.25 0.35 0.4]
Basically just compute the average over the values that we already have do not use the real duration values.

**Comment by royxue** [comment]
@julian-ramos 
The lifestyle contains various kinds of app, but I think your solution is good.

I only have one question: why not calculate the total durations? like
category A=[500,200,300]
category B=[300,200,500]
merged = [0.4, 0.2, 0.4]

I think this will be more accurate, isn't it?

**Comment by julian-ramos** [comment]
When you calculate using total duration the category with a higher duration
will have a higher weight on the total. By using the percent instead every
category only contributes 1/n to the total. Basically if we use the
duration, we will be seeing the contribution of the category with higher
duration mainly.

About the categories we covered everything then and you are good to go?

Did you check my note about the clustering in github?

On Mon, Dec 1, 2014 at 8:15 PM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> The lifestyle contains various kinds of app, but I think your solution is
> good.
> 
> I only have one question: why not calculate the total durations? like
> category A=[500,200,300]
> category B=[300,200,500]
> merged = [0.4, 0.2, 0.4]
> 
> I think this will be more accurate, isn't it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoyXue/MobileAnalysis/issues/3#issuecomment-65168383.

## 

Julian.

**Comment by royxue** [comment]
Yes, the clusGap(I created the scripts but didnt finish it.) and the standard deviation graph
I think it's really strange that on the graph, all the values are zero.
But im not sure what happened, maybe I think I should recheck the r scripts.
Once I get a accurate standard deviation graph, I can will go to do clusGap.

**Comment by royxue** [comment]
@julian-ramos 
in your description you left "Productivity" outside
I think maybe we should merge "Tools" into "Productivity" instead of the "Personalisation"?

Also we keep "Libraries and Demo" and "Education" alone, as they was sparse category, they are still sparse now, will this be ok?

**Comment by denzilferreira** [comment]
Yes it makes sense to keep tools and productivity together.

The libs can be isolated.

**Comment by royxue** [comment]
@denzilferreira 
Hi, Nice to meet you.
The libs you mean "Libraries" and "Education", right?

**Comment by denzilferreira** [comment]
Yes, nice to meet you! :) 
Sorry I replied on my phone and couldn't see all the categories. Yes, libraries and education should be separate.

**Comment by julian-ramos** [comment]
Hi Lijun,

Productivity and tools should not be together. Tools are not necessarily
for productivity they are mainly enhancements to your phone's sensors ans
those may or may not be for productivity. What's your reasoning to put
together tools and productivity?

**Comment by royxue** [comment]
@julian-ramos 
I quick scanned the apps under "Tools", I think you are right, the tools shouldn't be merged into productivity. I mistook the meaning of the category name "Tools"

**Comment by julian-ramos** [comment]
Ok, so leave productivity alone and put tools into personalization.

On Tue, Dec 2, 2014 at 9:43 AM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> I quick scanned the apps under "Tools", I think you are right, the tools
> shouldn't be merged into productivity. I mistook the meaning of the
> category name "Tools"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoyXue/MobileAnalysis/issues/3#issuecomment-65240275.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
I finished the merge part and just uploaded the data table.
Just mention that there are 1 bad data row with id 19.

**Comment by julian-ramos** [comment]
What do you mean by:

Just mention that there are 1 bad data row with id 19.

Though independent of the problem please fix it and let me know once you
get the clustering results

On Tue, Dec 2, 2014 at 10:07 AM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> I finished the merge part and just uploaded the data table.
> Just mention that there are 1 bad data row with id 19.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoyXue/MobileAnalysis/issues/3#issuecomment-65244124.

## 

Julian.

**Comment by royxue** [comment]
Oh, it means for that device_id the values is obviously wrong(too big/small), but I can fix it. I will inform you once I get the clustering results.
