### ISSUE TITLE
Heatmap Results

### ISSUE THREAD

**Issue by royxue** [royxue/MobileAnalysis#5]
## About Heatmaps:

I didnt find a good way to combine these graphs together, heatmap function didnt work well with par(which is used for combine plots in R), so I saved the graphs as separate graph. 
1. data_plot.png is the origin data heat map plot.
2. kmeans_heatmap.png: we knew that the result of kmeans algorithm is random, so in order to get a good heatmap graph, I set a boundary(0.36 from the kmeans graphs result we got before) when draw the  heatmap to get a good graph.
3. pam_heatmap.png: nothing special/
4. dbscan_heatmap.png: Finding proper values of MinPts and E is important for DBScan algorithm, the main strategy I use is: first set a MinPts, and then change the E to get different results then pick up the value combination whose result most close to kmeans and pam.  Here I use MinPts=7, and E=0.655.
5. hclust_heatmap: Here I use euclidean to draw the Hierarchical Clustering heatmap

**Comment by royxue** [comment]
from the heatmap of kmeans, pam, dbscan we can clearly see how are four cluster data like.
1. people who use apps mainly in morning and afternoon
2. people who use apps mainly in afternoon and evening
3. people who use apps mainly in evening and morning
4. people who use apps all day

**Comment by julian-ramos** [comment]
Hi Roy,

For #4 on About heatmaps: We don't want to find the value combination for dbscan that gives us the closest results to kmeans. That is wrong. We want to find the best combination that gives us the best clustering for dbscan.
