### ISSUE TITLE
Analysis Images

### ISSUE THREAD

**Issue by royxue** [royxue/MobileAnalysis#6]
@julian-ramos 
Hi Julian
Sorry for late reply, solving some stuff at home takes some time last week.
I uploaded some analysis result image based on category.
The image shows:
Category Total Duration
Category Total Times
Category Duration Per Time
Category Duration Percentage Per Time of Day
Category Time Percentage Per Time of Day
Category Duration Per Time Percentage Per Time of Day

later Im will upload the images based on user

**Comment by julian-ramos** [comment]
Thanks,

Questions:
What is the different between total duration and total times?

On Mon, Jan 19, 2015 at 12:34 AM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> Hi Julian
> Sorry for late reply, solving some stuff at home takes some time last week.
> I uploaded some analysis result image based on category.
> The image shows:
> Category Total Duration
> Category Total Times
> Category Duration Per Time
> Category Duration Percentage Per Time of Day
> Category Time Percentage Per Time of Day
> Category Duration Per Time Percentage Per Time of Day
> 
> later Im will upload the images based on user
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoyXue/MobileAnalysis/issues/6.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
Here the duration means how long have been used, times means how many times have been used

**Comment by royxue** [comment]
@julian-ramos 
do we need the analysis image of duration/times per user per category? or just duration/times per user is enough?

**Comment by julian-ramos** [comment]
the second

On Mon, Jan 19, 2015 at 8:45 PM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> do we need the analysis image of duration/times per user per category? or
> just duration/times per user is enough?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoyXue/MobileAnalysis/issues/6#issuecomment-70591720.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
I uploaded the total duration/times per user graphs.

**Comment by julian-ramos** [comment]
Hi Lijun,

The users graphs are impossible to understand in the current format please
use a histogram to present this information.

On Tue, Jan 20, 2015 at 8:27 AM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> I uploaded the total duration/times per user graphs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoyXue/MobileAnalysis/issues/6#issuecomment-70652563.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
Hi, Julian

hmmm, those graphs are already histograph(turned 90 degree), I think it's because there are too many users(and the device_id is too long) so the graph become too dense to understand?

**Comment by julian-ramos** [comment]
that is not a histogram. A histogram organizes the data depending on the
value of the variables. The values are definitely not organized on that
graph.

On Tue, Jan 20, 2015 at 10:57 AM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> Hi, Julian
> 
> hmmm, those graphs are already histograph(turned 90 degree), I think it's
> because there are too many users(and the device_id is too long) so the
> graph become too dense to understand?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoyXue/MobileAnalysis/issues/6#issuecomment-70676748.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
Just make sure if we are talking the same things, you mean the duration_usage_per_user.png and times_usage_per_user.png ?

**Comment by royxue** [comment]
@julian-ramos 
I uploaded the histogram

**Comment by julian-ramos** [comment]
can you make the x axis logarithmic for the duration histogram?

On Tue, Jan 20, 2015 at 12:09 PM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> I uploaded the histogram
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoyXue/MobileAnalysis/issues/6#issuecomment-70691769.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
hi
sorry, yesterday was late, so I went to sleep...

I just uploaded that histogram

**Comment by royxue** [comment]
@julian-ramos 
I will go to Thailand tomorrow, and I will return by 3rd Feb.
During this time I won't reply emails quickly.

**Comment by julian-ramos** [comment]
Ok no problem.

We are done with what I wanted you to do now I want to move on to create
more automated ways to analyze our databases and produce summaries of their
contents. Question is: Would you like to work on that?
You will be mainly contributing to a python library I already started which
has methods that produce certain data analysis over the data bases.

Let me know and I can tell you more about it,

Thanks,

On Mon, Jan 26, 2015 at 9:20 AM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> I will go to Thailand tomorrow, and I will return by 3rd Feb.
> During this time I won't reply emails quickly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/royxue/MobileAnalysis/issues/6#issuecomment-71466916.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
Hi, Julian
I arrived home yesterday night.

For your question, Im really interested in it. will the python library combine some other libraries like sql, data mining algorithm to offer easy ways getting the analysis result?

**Comment by julian-ramos** [comment]
yeah exactly, that is the plan, to automate data analysis on this kind of
databases including ML.

On Tue, Feb 3, 2015 at 10:09 PM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> Hi, Julian
> I arrived yesterday night.
> 
> For your question, Im really interested in it. will the python library
> combine some other libraries like sql, data mining algorithm to offer easy
> ways getting the analysis result?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/royxue/MobileAnalysis/issues/6#issuecomment-72782842.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
I think this would be very useful. Especially for the programming beginners. 
And it will make data analysis much easier

**Comment by royxue** [comment]
@julian-ramos 
have you already started the repo?

**Comment by julian-ramos** [comment]
yes I did. I haven't thought of how could you collaborate.

Currently there is an Ms student working on the summary section, looking
what could be the best information to convey and how using R-Markdown.

I think in your case you could go through her code and optimize it. The
idea is that this code for creating this summaries has to work for huge
databases. Would you like to do that?

On Thu, Feb 5, 2015 at 8:42 PM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> have you already started the repo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/royxue/MobileAnalysis/issues/6#issuecomment-73166759.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
it sounds good, by this way, I can get familiar with the library ;)

**Comment by julian-ramos** [comment]
Ok then, you can start looking it at right away. I already wrote some
functions that reproduce some of your work though I didn't use your code in
most cases.

Here is the repo https://github.com/julian-ramos/awareAnalysis

I want you to start with the sessionsExtract method.

There are a set of rules though:
- No CSV files, everything must be self contained
- No absurd number of tables created on the database
- Test everything! Since you are going to work on optimizing this method
  I need to see speed tests of the current method versus your version.

So, I don't want you to modify directly the method that I have but instead
to create a new optimized version of it, that way we can always choose
which one to use to compare the results.

Last, start your own branch and do not merge to the master branch I will be
in charge of that.

I will be adding you now as a contributor.

On Thu, Feb 5, 2015 at 9:08 PM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> it sounds good, by this way, I can get familiar with the library ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/royxue/MobileAnalysis/issues/6#issuecomment-73170012.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
OK, I got in.
i think we should better add a .gitignore file to ignore the .pyc files, these will make the repo really messy.
